POST https://crud-em-node.onrender.com/videos
Content-Type: application/json

{
    "title":"video node",
    "description":"Primeiro vídeo",
    "duration": 180
}

###

GET https://crud-em-node.onrender.com/videos


###

PUT https://crud-em-node.onrender.com/videos/
Content-Type: application/json

{
    "title":"Video modificado",
    "description":"MODIFICADOOOOOOOOOOOO",
    "duration": 2000
}

###

DELETE https://crud-em-node.onrender.com/videos/